default_language_version:
  python: python3

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v4.5.0'
    hooks:
      - id: check-toml
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.3.5'
    hooks:
      - id: ruff
        # Explicitly setting config to prevent Ruff from using `pyproject.toml` in sub packages.
        args: [ '--fix', '--exit-non-zero-on-fix', '--config', 'pyproject.toml' ]
      - id: ruff-format
        args: [ '--config', 'pyproject.toml' ]

#  - repo: local
#    hooks:
#      - id: mypy
#        name: mypy
#        entry: poetry run mypy
#        args: ["--config-file", "pyproject.toml"]
#        files: "core"  # start with the core being type checked
#        language: system
#        types: [ python ]
#        require_serial: true
