name: Automatically add or remove labels
on:
  issues:
    types:
      - opened
jobs:
  show-metadata:
    runs-on: ubuntu-latest
    steps:
    # Use environment variable to print the metadata (cf. https://github.com/actions/runner/issues/1656#issuecomment-1030077729).
    - name: Show metadata
      run: echo $JSON
      env:
        JSON: ${{ toJson(github.event) }}
  add-label:
    if: ${{ github.event.comment.user.login != 'tillahoffmann' }}
    runs-on: ubuntu-latest
    steps:
    - name: Add label
      uses: actions-ecosystem/action-add-labels@v1
      with:
        labels: 'ðŸ‘€ requires attention'
  remove-label:
    if: ${{ github.event.comment.user.login == 'tillahoffmann' }}
    runs-on: ubuntu-latest
    steps:
    - name: Remove label
      uses: actions-ecosystem/action-remove-labels@v1
      with:
        labels: 'ðŸ‘€ requires attention'
