# Contrinuous Integration for community modules

name: modules

on:
  push:
    branches: [ main ]
    paths:
      - "testcontainers/**"
      - "!testcontainers/core/**"
  pull_request:
    branches: [ main ]
    paths:
      - "testcontainers/**"
      - "!testcontainers/core/**"

jobs:
  track-modules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout contents
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # recommended by tj-actions/changed-files
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v42
        with:
          path: "./testcontainers"
          diff_relative: true
          dir_names: true
          dir_names_exclude_current_dir: true
          json: true
      - name: Compute modules from files
        id: compute-changes
        run: |
          modules=$(echo "${{ steps.changed-files.outputs.all_changed_files }}" |  jq '.[] | split("/") | first' | jq -s -c '[.[] | select(. != "core")] | unique'))
          echo "computed_modules=$modules"
          echo "computed_modules=$modules" >> $GITHUB_OUTPUT
    outputs:
      changed_modules: ${{ steps.compute-changes.outputs.computed_modules }}
  test:
    needs: [track-modules]
    if: ${{ needs.track-modules.outputs.changed_modules != '[]' }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.11" ]
        module: ${{ fromJSON(needs.track-modules.outputs.changed_modules) }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout contents
        uses: actions/checkout@v4
      - name: Set up Python
        uses: ./.github/actions/setup-env
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Python dependencies
        run: poetry install -E ${{ matrix.module }}
      - name: Run tests
        run: make tests/${{ matrix.module }}
