name: Release Please

env:
  UV_FROZEN: "1"   # use lock file as is
  UV_NO_EDITABLE: "1"  # test the build package, not the dev installation

on:
  push:
    branches: [ main ]

jobs:
  release:
    runs-on: ubuntu-22.04
    outputs:
      release_created: ${{ steps.track-release.outputs.release_created }}
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: track-release
        with:
          manifest-file: .github/.release-please-manifest.json
          config-file: .github/release-please-config.json
  publish:
    runs-on: ubuntu-22.04
    environment: release
    permissions:
      id-token: write
    needs:
      - release
    if: ${{ needs.release.outputs.release_created }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: ./.github/actions/setup-env
      - name: build package
        run: uv build
      # this action uploads packages from the `dist/` directory, which uv has built in the previous step
      # usable once we set up trusted publishing, see https://docs.pypi.org/trusted-publishers/using-a-publisher/
      - name: push package
        uses: pypa/gh-action-pypi-publish@release/v1
